### ISSUE TITLE
I use your script with Python 2.7.9 with Win7Pro the download is correct, but the zip file downloaded is damaged. 

### ISSUE THREAD

**Issue by Saimor** [superalex/py-wetransfer#12]

**Comment by szepeviktor** [comment]
[Here is](https://www.wetransfer.com/downloads/a922a9a14f9b136d3745643f04b6659820150107203812/e19cf4df48f5ad05b282e1bd4429656020150107203812/25d857) wetransfer.py.
When downloading on Windows it get LFCR line endings, on Linux the original LF.

@Saimor Please consider putting your sentence in the comment box and rename the issue to something like **Downloaded ZIP damaged on Windows 7 Pro**

**Comment by szepeviktor** [comment]
And really on Windows it get corrupted.
[py-wetransfer.zip](https://www.wetransfer.com/downloads/8711d390fd6e3e5b61abab1b2b6c04be20150107205206/4b6e87e2aa5ee907b3d7e1d033c435c620150107205206/82e8c6)

**Comment by szepeviktor** [comment]
Solution: https://github.com/superalex/py-wetransfer/pull/13
Put a `b` in `open(file_name, 'w')`.

**Comment by superalex** [comment]
Thanks @szepeviktor I've just merged your PR so @Saimor it should be working now on windows too.

**Comment by Saimor** [comment]
Thank you
