### ISSUE TITLE
doesn't work anymore ?

### ISSUE THREAD

**Issue by Aiexis** [superalex/py-wetransfer#16]
Hello
I have an issue since today while trying to download.

# python wetransfer.py -u https://www.wetransfer.com/downloads/88d55358d83fdda2aa4ff2ff6c0cdb4220160106184103/f1dccfc494c72d5f42e3ace7bc2700a520160106184103/09e850
Downloading https://www.wetransfer.com/api/v1/transfers/88d55358d83fdda2aa4ff2ff6c0cdb4220160106184103/download?recipient_id=f1dccfc494c72d5f42e3ace7bc2700a520160106184103&security_hash=09e850&password=&ie=false...
Traceback (most recent call last):
  File "wetransfer.py", line 109, in <module>
    main(sys.argv[1:])
  File "wetransfer.py", line 101, in main
    download(file_id, recipient_id, security_hash)
  File "wetransfer.py", line 26, in download
    content_info_string = parse_qs(urlparse(download_data['direct_link']).query)['response-content-disposition'][0]
KeyError: 'response-content-disposition'

Any idea ?
Thank you

**Comment by szepeviktor** [comment]
The response is `{u'direct_link': u'https://download.wetransfer.com/wetransfer-eu1/88d55`
but `download_data.has_key('direct_link')` is false.

**Comment by Aiexis** [comment]
Mmm... sorry ?
What do I have to do exactly ?

**Comment by szepeviktor** [comment]
I've just printed `download_data` and made I remark.
This is very dangerous, because I don't speak python
```python
    print 'Downloading {0}...'.format(url)
    #if download_data.has_key('direct_link'):
    if ('direct_link' in download_data):
        #content_info_string = parse_qs(urlparse(download_data['direct_link']).query)['response-content-disposition'][0]
        #file_name = re.findall('filename="(.*?)"', content_info_string)[0].encode('ascii', 'ignore')
        file_name = parse_qs(urlparse(download_data['direct_link']).query)['filename'][0].encode('ascii', 'ignore')
        r = requests.get(download_data['direct_link'], stream=True)
```
It runs for me (Python 2.7.9)

**Comment by szepeviktor** [comment]
@superalex It seems WeTransfer has change their HTTP headers.
Please consider adding a bunch of `if`-s to HTTP parsing.

**Comment by Gidrek** [comment]
I have created a pull request with changes to fix it

**Comment by Aiexis** [comment]
Thank you szepeviktor, it works for me too

>print "Downloading {0}...".format(url)
    if download_data.has_key('direct_link'):
        file_name = parse_qs(urlparse(download_data['direct_link']).query)['filename'][0].encode('ascii', 'ignore')
		r = requests.get(download_data['direct_link'], stream=True)

**Comment by superalex** [comment]
Great!, thank you very much!, I've just merged the PR :)
