### ISSUE TITLE
direct_link problem

### ISSUE THREAD

**Issue by rzegwaard** [superalex/py-wetransfer#22]
Hi,

I had a problem with the direct_link. The script couldn't find the filename.

Solved it by changing a piece of code to:

```
if 'direct_link' in download_data:
    direct_link_path = urlparse(download_data['direct_link']).path
    direct_link_path = direct_link_path.split('/')
    file_name = direct_link_path[-1]

    r = requests.get(download_data['direct_link'], stream=True)
else:
```

Using:
Python 2.7.11 
OS X 10.10.5

**Comment by szepeviktor** [comment]
@superalex Could you take a look at it for 10 minutes?

**Comment by rzegwaard** [comment]
Sorry, i don't understand what to look at...

**Comment by szepeviktor** [comment]
I was mentioning @superalex to update the code.

**Comment by superalex** [comment]
Sorry for the delay!

I've just included your suggested code in py-wetransfer, thank you very much @rzegwaard 

Regards,
