### ISSUE TITLE
New way of getting directlink from weTransfer

### ISSUE THREAD

**Issue by Sicos1977** [superalex/py-wetransfer#28]
If someone is wondering why weTransfer is nog working anymore since this weekend (2017-07-15). It is because weTransfer changed some things. Normally you would get the json object with directlink by making an URL like this.

`https://wetransfer.com/api/ui/transfers/XXXXXXXXXX/ZZZZZZ/download?recipient_id=YYYYYYYYYY`

But now you have to do it like this:

```
https://wetransfer.com/api/ui/transfers/XXXXXXXXXX/ZZZZZZ/download as a POST request. In the same request you need to upload the recipient id wrapped in a json object like this.

{"recipient_id":"<recipient_id>"}

```

**Comment by lrapetti** [comment]
@Sicos1977 Is this fixed somewhere?
